name: Go Build and Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntuランナーを使用

    steps:
    # ソースコードをチェックアウト
    - name: Checkout code
      uses: actions/checkout@v3

    # Goのセットアップ
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.2'  # 使用するGoのバージョン

    # 依存関係を解決（go mod tidy）
    - name: Install dependencies
      run: go mod tidy

    # Goのビルド（./prayという実行ファイルを作成）
    - name: Build the Go project
      run: go build -o pray ./main.go  # main.goがプロジェクトルートにあることを想定

    # GitHub Releaseにアップロード
    - name: Upload binary to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: pray  # ビルドした実行ファイル
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHubのアクセストークンを使用

